name: Run jest tests
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run ci
        run: npm ci

      - name: run jest
        run: npm test

      - name: tests passed
        if: ${{ success() }}
        run: echo tests passed

      - name: tests failed
        if: ${{ failure() }}
        run: echo tests failed
